### ISSUE TITLE
:q crashes the GUI

### ISSUE THREAD

**Issue by osa1** [equalsraf/neovim-qt#12]
I'm getting this error message: `Neovim fatal error "The Neovim process has crashed"`

Note that GUI doesn't terminate when this happens, I have to kill it manually.

**Comment by equalsraf** [comment]
@osa1 I'm still thinking how to handle those cases. The GUI should on a clean exit, but it stays open on a crash. I've pushed a patch that was missing to master. You should be seeing this.

![qtcrash](https://cloud.githubusercontent.com/assets/715238/7324939/a5ce710a-eab2-11e4-8552-9e5a8bf69752.png)

**Comment by equalsraf** [comment]
See neovim/neovim#2466, neovim/neovim#2648 and neovim/neovim#2663

**Comment by equalsraf** [comment]
This should be fixed now, a patch has been merged upstream.

**Comment by raghur** [comment]
Still having this issue with the latest neovim and neovim-qt binaries from appveyor.

**Comment by equalsraf** [comment]
@raghur are you still seeing this? 

```
NVIM 0.0.0-alpha+201509220803 (compiled Sep 22 2015 09:38:49)                                  
Commit: 1ba081a6735e74446d5e9e05d0fb0bf9cca31f63 
```

**Comment by raghur** [comment]
@equalsraf  - checked version of `nvim`  is from Sep 13th on appveyor
```
E:\Utils\neovim-qt>nvim --version
NVIM 0.0.0-alpha+201509132337 (compiled Sep 13 2015 22:46:28)
Commit: caf8b9552eb8122a6b58e7f7e69e8ab5ddd46b1d
```
So maybe that's the issue - but I don't see a later build there. Where can I find the build you're running?

**Comment by equalsraf** [comment]
> Where can I find the build you're running?

@raghur the Appveyor Neovim builds were stuck for a while due to a bug, but it is rebuilding right now (shouldn't take more than 10min).

**Comment by raghur** [comment]
Updated from appveyor. It doesn't crash anymore. However, now if I type `:q<Enter>`, it just sits there - and then needs another <Enter> key before the window closes.

**Comment by jasonwilliams200OK** [comment]
FWIW, to interact with cloud instance, you can enable [RDP for AppVeyor worker](http://www.appveyor.com/docs/how-to/rdp-to-build-worker). It will show the RDP connection settings at the beginning of log.

**Comment by equalsraf** [comment]
@jasonwilliams200OK awesome, I was not aware of that

**Comment by equalsraf** [comment]
Closing this, the additional issue is in https://github.com/equalsraf/neovim-qt/issues/53
