### ISSUE TITLE
Colours are off for nvim-qt, working in terminal nvim

### ISSUE THREAD

**Issue by agauniyal** [equalsraf/neovim-qt#124]
![2016-05-18-122613_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/15349954/fe3e68c6-1cf3-11e6-89c4-93aa8a370237.png)
![2016-05-18-122634_1366x768_scrot](https://cloud.githubusercontent.com/assets/7630575/15349956/0128b000-1cf4-11e6-9be1-78cac1a8012e.png)

**Comment by agauniyal** [comment]
Take a look at modeline, you'll see the terminal one highlighted with blue color, while nvim-qt remains unhighlighted. Otherwise editor colors are working. Also is there an option to reduce font size in nvim-qt?

**Comment by equalsraf** [comment]
@agauniyal there is a `:Guifont` command to set the font (also works from ginit.vim)

**Comment by ronisbr** [comment]
@equalsraf I see that Guifont command is available only in the staging version. As far as I known, the v0.1.2 was released before the plugin with this command right? Is there any timeline to release a new version?

**Comment by equalsraf** [comment]
Did this get fixed with the latest master?

> @equalsraf I see that Guifont command is available only in the staging version.

In Unix it should be available in the latest release tag. In the windows release zip :GuiFont is not working (wait for #133)

**Comment by Atraii** [comment]
I'm still seeing the color problem, if that is what you were referring to.

**Comment by agauniyal** [comment]
Nope not fixed yet.

**Comment by equalsraf** [comment]
does #151 help with this?
